### PR TITLE
remove example-c resource

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lahenn** [comment]
atlantis plan

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
```
exit status 1
Checking plan against the following policies: 
  example-conf-tests
FAIL - <redacted plan file> - main - null resources with name 'example-a' cannot be created

1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions

```
* :heavy_check_mark: To **approve** failing policies an authorized approver can comment:
    * `atlantis approve_policies`
* :repeat: Or, address the policy failure by modifying the codebase and re-planning.

**Review by lhenn-au — APPROVED** [review]

**Comment by lahenn** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

**Apply Failed**: All policies must pass for project before running apply

**Comment by lhenn-au** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
null_resource.example-a: Creating...
null_resource.example-b: Creating...
null_resource.example-b: Creation complete after 0s [id=5577006791947779410]
null_resource.example-a: Creation complete after 0s [id=8674665223082153551]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```
</details>

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

```diff
Checking plan against the following policies: 
  example-conf-tests

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lahenn** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

```diff
null_resource.example-b: Creating...
null_resource.example-b: Creation complete after 0s [id=5577006791947779410]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
```
exit status 1
Checking plan against the following policies: 
  example-conf-tests
FAIL - <redacted plan file> - main - null resources with name 'example-a' cannot be created

1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions

```
* :heavy_check_mark: To **approve** failing policies an authorized approver can comment:
    * `atlantis approve_policies`
* :repeat: Or, address the policy failure by modifying the codebase and re-planning.

**Comment by lahenn** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
atlantis approve_policies

**Comment by lhenn-au** [comment]
Approved Policies for 1 projects:

1. dir: `terraform-a` workspace: `default`

**Comment by lahenn** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
null_resource.example-a: Creating...
null_resource.example-b: Creating...
null_resource.example-a: Creation complete after 0s [id=5577006791947779410]
null_resource.example-b: Creation complete after 0s [id=8674665223082153551]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```
</details>

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
```
exit status 1
Checking plan against the following policies: 
  example-conf-tests
Error: running test: load: loading policies: load: 2 errors occurred during loading:
stat ./policies: no such file or directory
stat ./policies/: no such file or directory

```
* :heavy_check_mark: To **approve** failing policies an authorized approver can comment:
    * `atlantis approve_policies`
* :repeat: Or, address the policy failure by modifying the codebase and re-planning.

**Comment by lahenn** [comment]
terraform plan

**Comment by lhenn-au** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
<details><summary>Show Output</summary>

```
exit status 1
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/24/default/terraform-a

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/24/default/terraform-a

default.json
default.tfplan
terraform.tfstate
test.tf

Checking plan against the following policies: 
  example-conf-tests
Error: running test: load: loading policies: load: 2 errors occurred during loading:
stat ./policies: no such file or directory
stat ./policies/: no such file or directory

```
</details>

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/24/default/terraform-a

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/24/default/terraform-a

default.json
default.tfplan
terraform.tfstate
test.tf

Checking plan against the following policies: 
  example-conf-tests

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://5422-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d terraform-a`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://259d-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
```
exit status 1
Checking plan against the following policies: 
  example-conf-tests
Error: running test: parse files: get file info: stat echo: no such file or directory

```
* :heavy_check_mark: To **approve** failing policies an authorized approver can comment:
    * `atlantis approve_policies`
* :repeat: Or, address the policy failure by modifying the codebase and re-planning.

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://afbb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

```diff
Checking plan against the following policies: 
  example-conf-tests

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://afbb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://afbb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
<details><summary>Show Output</summary>

```
exit status 1
Checking plan against the following policies: 
  example-conf-tests
Usage:
  conftest test <path> [path [...]] [flags]

Flags:
      --all-namespaces        Test policies found in all namespaces
      --capabilities string   Path to JSON file that can restrict opa functionality against a given policy. Default: all operations allowed
      --combine               Combine all config files to be evaluated together
  -d, --data strings          A list of paths from which data for the rego policies will be recursively loaded
      --fail-on-warn          Return a non-zero exit code if warnings or errors are found
  -h, --help                  help for test
      --ignore string         A regex pattern which can be used for ignoring paths
      --junit-hide-message    Do not include the violation message in the JUnit test name
  -n, --namespace strings     Test policies in a specific namespace (default [main])
      --no-color              Disable color when printing
      --no-fail               Return an exit code of zero even if a policy fails
  -o, --output string         Output format for conftest results - valid options are: [stdout json tap table junit github] (default "stdout")
      --parser string         Parser to use to parse the configurations. Valid parsers: [cue dockerfile edn hcl1 hcl2 hocon ignore ini json jsonnet properties spdx toml vcl xml yaml dotenv]
  -p, --policy strings        Path to the Rego policy files directory (default [policy])
      --suppress-exceptions   Do not include exceptions in output
      --trace                 Enable more verbose trace output for Rego queries
  -u, --update strings        A list of URLs can be provided to the update flag, which will download before the tests run
Error: missing required arguments

```
</details>

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://afbb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

```diff
Checking plan against the following policies: 
  example-conf-tests

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://afbb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://580e-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for 2 projects:

1. dir: `terraform-a` workspace: `default`
1. dir: `terraform` workspace: `default`

### 1. dir: `terraform-a` workspace: `default`
<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://580e-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
### 2. dir: `terraform` workspace: `default`
**Plan Failed**: This project is currently locked by an unapplied plan from pull #1. To continue, delete the lock from #1 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for 2 projects:

1. dir: `terraform-a` workspace: `default`
1. dir: `terraform` workspace: `default`

### 1. dir: `terraform-a` workspace: `default`
<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://580e-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
### 2. dir: `terraform` workspace: `default`
**Plan Failed**: This project is currently locked by an unapplied plan from pull #1. To continue, delete the lock from #1 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-a` workspace: `default`

**Pull request merged**
