### PR TITLE
update tf a resource

### PR DESCRIPTION
**Pull request by lhenn-au**

### CODE REVIEW

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://580e-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
```
running "$DIR/atlantis-example/pull-policies.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a": exit status 127: running "$DIR/atlantis-example/pull-policies.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a": 
sh: /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a/atlantis-example/pull-policies.sh: No such file or directory


```
* :heavy_check_mark: To **approve** failing policies an authorized approver can comment:
    * `atlantis approve_policies`
* :repeat: Or, address the policy failure by modifying the codebase and re-planning.

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://580e-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
<details><summary>Show Output</summary>

```
exit status 1
hello world
/Users/laurahenn/atlantis-policy-test/policies does exist.
Already on 'master'
Your branch is up to date with 'origin/master'.
From github.com:lhenn-au/atlantis-example
   4307a6e..039f346  master        -> origin/master
 + b7bcbb4...1631d63 test-policies -> origin/test-policies  (forced update)
Updating 4307a6e..039f346
Fast-forward
 my-custom-script.sh           |  1 -
 pull-policies.sh              | 13 +++++++++++++
 server-side-config.yaml       | 16 +++++++++-------
 terraform-a/test.tf           |  2 --
 terraform/.terraform.lock.hcl | 23 +++++++++++++++++++++++
 terraform/_backend.tf         |  8 ++++++++
 terraform/_provider.tf        | 17 +++++++++++++++++
 terraform/test.tf             |  2 +-
 8 files changed, 71 insertions(+), 11 deletions(-)
 delete mode 100755 my-custom-script.sh
 create mode 100755 pull-policies.sh
 create mode 100644 terraform/_backend.tf
 create mode 100644 terraform/_provider.tf

Checking plan against the following policies: 
  example-policies
Error: running test: parse files: get file info: stat <redacted plan file>: no such file or directory

```
</details>

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://580e-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
```
exit status 1
hello world
/Users/laurahenn/atlantis-policy-test/policies does exist.
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.

dir is now /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a

Checking plan against the following policies: 
  example-policies
Error: running test: parse files: get file info: stat <redacted plan file>: no such file or directory

```
* :heavy_check_mark: To **approve** failing policies an authorized approver can comment:
    * `atlantis approve_policies`
* :repeat: Or, address the policy failure by modifying the codebase and re-planning.

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://580e-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
<details><summary>Show Output</summary>

```
exit status 1
hello world
/Users/laurahenn/atlantis-policy-test/policies does exist.
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.

dir is now /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a

Checking plan against the following policies: 
  example-policies
FAIL - <redacted plan file> - main - null resources with name 'example-a' cannot be created

1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions

```
</details>

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
<details><summary>Show Output</summary>

```
exit status 1
hello world
/Users/laurahenn/atlantis-policy-test/policies does exist.
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.

dir is now /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a

Checking plan against the following policies: 
  example-policies
FAIL - <redacted plan file> - main - null resources with name 'example-a' cannot be created

1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions

```
</details>

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
hello world
/Users/laurahenn/atlantis-policy-test/policies does exist.
Already on 'master'
Your branch is up to date with 'origin/master'.
From github.com:lhenn-au/atlantis-example
   1631d63..cd8d8f6  test-policies -> origin/test-policies
Already up to date.

dir is now /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a

Checking plan against the following policies: 
  example-policies

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d terraform-a`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
Retrieving policies
pulling master branch of /Users/laurahenn/atlantis-policy-test/policies
Already on 'master'
Your branch is up to date with 'origin/master'.
From github.com:lhenn-au/atlantis-example
   cd8d8f6..efc8588  test-policies -> origin/test-policies
Already up to date.

dir is now /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/25/default/terraform-a

Checking plan against the following policies: 
  example-policies

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d terraform-a`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by lahenn — APPROVED** [review]

**Comment by lhenn-au** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
null_resource.example-b: Creating...
null_resource.example-c: Creating...
null_resource.example-b: Creation complete after 0s [id=5577006791947779410]
null_resource.example-c: Creation complete after 0s [id=8674665223082153551]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```
</details>

**Comment by lhenn-au** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-a` workspace: `default`

**Pull request merged**
