### PR TITLE
Terraform a custom wf

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a

Cloning into 'atlantis-example'...

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a

hello world


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://b6bb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for 2 projects:

1. dir: `terraform-a` workspace: `default`
1. dir: `terraform-b` workspace: `default`

### 1. dir: `terraform-a` workspace: `default`
<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a

Cloning into 'atlantis-example'...

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a

hello world


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://b6bb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
### 2. dir: `terraform-b` workspace: `default`
<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-b

Cloning into 'atlantis-example'...

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-b
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-b

hello world


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-b`
* :put_litter_in_its_place: To **delete** this plan click [here](https://b6bb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-b%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-b`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by gozy-au** [comment]
atlantis plan -d terraform-a

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a": exit status 128: running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a": 
fatal: destination path 'atlantis-example' already exists and is not an empty directory.

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a

```

**Comment by gozy-au** [comment]
atlantis unlock

**Comment by gozy-au** [comment]
atlantis plan -d terraform-a

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -upgrade" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a": exit status 1
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a

Cloning into 'atlantis-example'...

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/11/default/terraform-a

hello world


Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/null...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/null:
could not connect to registry.terraform.io: Failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)


```
</details>

**Comment by lhenn-au** [comment]
Ran Apply for 0 projects:

**Comment by gozy-au** [comment]
atlantis apply -d terraform-a

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by lhenn-au — APPROVED** [review]

**Pull request merged**
