### PR TITLE
add resource c to terraform-b

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-b` workspace: `default`

<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

Cloning into 'atlantis-example'...

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

hello world


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-b`
* :put_litter_in_its_place: To **delete** this plan click [here](https://3161-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-b%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-b`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by adminco** [comment]
atlantis plan -d terraform-b

**Comment by adminco** [comment]
atlantis unlock

**Comment by lhenn-au** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by adminco** [comment]
atlantis plan -d terraform-b

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-b` workspace: `default`

**Plan Error**
```
running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b": exit status 128: running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b": 
fatal: destination path 'atlantis-example' already exists and is not an empty directory.

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

```

**Comment by lhenn-au** [comment]
atlantis plan -d terraform-b

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-b` workspace: `default`

**Plan Error**
```
running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b": exit status 128: running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b": 
fatal: destination path 'atlantis-example' already exists and is not an empty directory.

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

```

**Comment by lhenn-au** [comment]
atlantis unlock

**Comment by lhenn-au** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-b` workspace: `default`

**Plan Error**
```
running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b": exit status 128: running "git clone git@github.com:lhenn-au/atlantis-example.git" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b": 
fatal: destination path 'atlantis-example' already exists and is not an empty directory.

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

```

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-b` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -upgrade" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b": exit status 1
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

fatal: destination path 'atlantis-example' already exists and is not an empty directory.

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

hello world


Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/null...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/null:
could not connect to registry.terraform.io: Failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)


```
</details>

**Comment by lhenn-au** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-b` workspace: `default`

<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

fatal: destination path 'atlantis-example' already exists and is not an empty directory.

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

hello world


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-b`
* :put_litter_in_its_place: To **delete** this plan click [here](https://3161-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-b%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-b`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by adminco** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-b` workspace: `default`

<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

fatal: destination path 'atlantis-example' already exists and is not an empty directory.

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b
atlantis-example
test.tf

dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/13/default/terraform-b

hello world


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-b`
* :put_litter_in_its_place: To **delete** this plan click [here](https://3161-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-b%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-b`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by adminco** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-b` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by lhenn-au — APPROVED** [review]

**Comment by adminco** [comment]
atlantis apply

**Comment by adminco** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-b` workspace: `default`

<details><summary>Show Output</summary>

```diff
null_resource.example-b: Creating...
null_resource.example-c: Creating...
null_resource.example-b: Creation complete after 0s [id=5577006791947779410]
null_resource.example-c: Creation complete after 0s [id=8674665223082153551]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```
</details>

**Comment by lhenn-au** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-b` workspace: `default`

**Pull request closed without merging**
