### PR TITLE
policies demo

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

  # null_resource.example-d will be created
+ resource "null_resource" "example-d" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

**Policy Check Error**
```
running "$PULL_POLICY_SCRIPT" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/26/default/terraform-a": exit status 126: running "$PULL_POLICY_SCRIPT" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/26/default/terraform-a": 
sh: /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/26/default/policies: is a directory


```
* :heavy_check_mark: To **approve** failing policies an authorized approver can comment:
    * `atlantis approve_policies`
* :repeat: Or, address the policy failure by modifying the codebase and re-planning.

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

  # null_resource.example-d will be created
+ resource "null_resource" "example-d" {
      + id = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Policy Check for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
Retrieving policies
pulling master branch of /Users/laurahenn/atlantis-policy-test/policies
Already on 'master'
Your branch is up to date with 'origin/master'.
From github.com:lhenn-au/atlantis-example
   039f346..b531857  master        -> origin/master
 * [new branch]      policies-demo -> origin/policies-demo
Updating 039f346..b531857
Fast-forward
 pull-policies.sh        | 12 +++++++++---
 server-side-config.yaml | 13 +++++++------
 terraform-a/test.tf     |  2 +-
 3 files changed, 17 insertions(+), 10 deletions(-)

dir is now /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/26/default/terraform-a

Checking plan against the following policies: 
  example-policies

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://db01-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d terraform-a`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-a` workspace: `default`

**Pull request merged**
