### PR TITLE
remove null resource

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lahenn** [comment]
atlantis plan

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #27. To continue, delete the lock from #27 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://45d0-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

```diff

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://45d0-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # null_resource.example-c will be destroyed
- resource "null_resource" "example-c" {
      - id = "5577006791947779410" -> null
    }

  # null_resource.example-cc will be created
+ resource "null_resource" "example-cc" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://45d0-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # null_resource.example-c will be destroyed
- resource "null_resource" "example-c" {
      - id = "5577006791947779410" -> null
    }

  # null_resource.example-cc will be created
+ resource "null_resource" "example-cc" {
      + id = (known after apply)
    }

  # null_resource.example-d will be created
+ resource "null_resource" "example-d" {
      + id = (known after apply)
    }

Plan: 2 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://45d0-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 2 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # null_resource.example-c will be destroyed
- resource "null_resource" "example-c" {
      - id = "5577006791947779410" -> null
    }

  # null_resource.example-cc will be created
+ resource "null_resource" "example-cc" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://45d0-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # null_resource.example-c will be destroyed
- resource "null_resource" "example-c" {
      - id = "5577006791947779410" -> null
    }

  # null_resource.example-cc will be created
+ resource "null_resource" "example-cc" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://45d0-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-a` workspace: `default`

**Pull request closed without merging**
