### PR TITLE
add terraform-a, update server config

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://24e3-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "./my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": exit status 127: running "./my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": 
sh: ./my-custom-script.sh: No such file or directory


```

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "$DIR/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": exit status 127: running "$DIR/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": 
sh: /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a/my-custom-script.sh: No such file or directory

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a

```

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "$DIR/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": exit status 127: running "$DIR/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": 
sh: /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a/my-custom-script.sh: No such file or directory

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a

```

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "../../../my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": exit status 127: running "../../../my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": 
sh: ../../../my-custom-script.sh: No such file or directory

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a

1
8

```

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "../../../../my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": exit status 127: running "../../../../my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": 
sh: ../../../../my-custom-script.sh: No such file or directory

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a

atlantis-example

```

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "./atlantis-example/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": exit status 127: running "./atlantis-example/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": 
sh: ./atlantis-example/my-custom-script.sh: No such file or directory

Cloning into 'atlantis-example'...

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a

atlantis-example
test.tf

```

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
```
running "$DIR/atlantis-example/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": exit status 127: running "$DIR/atlantis-example/my-custom-script.sh" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a": 
sh: /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a/atlantis-example/my-custom-script.sh: No such file or directory

Cloning into 'atlantis-example'...

/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a
atlantis-example
test.tf

```

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/8/default/terraform-a
test.tf


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://b6bb-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lahenn** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by lhenn-au — APPROVED** [review]

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform-a` workspace: `default`

```diff
null_resource.example-a: Creating...
null_resource.example-a: Creation complete after 0s [id=5577006791947779410]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```

**Comment by lahenn** [comment]
atlantis apply -d terraform-a

**Comment by lhenn-au** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-a` workspace: `default`

**Comment by lhenn-au** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
