### PR TITLE
rename null resource

### PR DESCRIPTION
**Pull request by lhenn-au**

### CODE REVIEW

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://c0b7-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
atlantis apply -d terraform

**Comment by lhenn-au** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff
null_resource.example-a: Creating...
null_resource.example-a: Creation complete after 0s [id=5577006791947779410]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: terraform.tfstate

```

**Comment by lhenn-au** [comment]
terraform show

**Comment by lhenn-au** [comment]
terraform plan

**Comment by lhenn-au** [comment]
atlantis apply -d terraform

**Comment by lahenn** [comment]
atlantis unlock

**Comment by lhenn-au** [comment]
Atlantis commands can't be run on closed pull requests

**Comment by lahenn** [comment]
atlantis apply

**Comment by lhenn-au** [comment]
Atlantis commands can't be run on closed pull requests

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
