### PR TITLE
add d to terraform-a

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #20. To continue, delete the lock from #20 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform init -input=false -upgrade" in "/Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/21/default/terraform-a": exit status 1
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/21/default/terraform-a


Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/null...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/null:
could not connect to registry.terraform.io: Failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)


```
</details>

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
Ran Plan for dir: `terraform-a` workspace: `default`

<details><summary>Show Output</summary>

```diff
dir is /Users/laurahenn/.atlantis/repos/lhenn-au/atlantis-example/21/default/terraform-a


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-a will be created
+ resource "null_resource" "example-a" {
      + id = (known after apply)
    }

  # null_resource.example-b will be created
+ resource "null_resource" "example-b" {
      + id = (known after apply)
    }

  # null_resource.example-c will be created
+ resource "null_resource" "example-c" {
      + id = (known after apply)
    }

  # null_resource.example-d will be created
+ resource "null_resource" "example-d" {
      + id = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-a`
* :put_litter_in_its_place: To **delete** this plan click [here](https://c549-184-163-75-132.ngrok.io/lock?id=lhenn-au%252Fatlantis-example%252Fterraform-a%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-a`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by lhenn-au** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-a` workspace: `default`

**Pull request closed without merging**
