### PR TITLE
remove some resource

### PR DESCRIPTION
**Pull request by lahenn**

### CODE REVIEW

**Comment by lhenn-au** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by lahenn** [comment]
atlantis plan

**Comment by lhenn-au** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `I've be...` into raw.RepoCfg
```

**Comment by lhenn-au** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `I've be...` into raw.RepoCfg
```

**Comment by lhenn-au** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `I've be...` into raw.RepoCfg
```

**Comment by lhenn-au** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: line 3: could not find expected ':'
```

**Pull request merged**
